skip_tags: true

environment:
  PYTHON: C:\\Python37-x64

  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_LOG_RUN_TO_OUTPUT: 1

  CONAN_REFERENCE: xerces-c/3.2.3+0
  CONAN_USERNAME: odant
  CONAN_CHANNEL: testing
  CONAN_STABLE_CHANNEL: stable

  CONAN_UPLOAD: https://conan.kysa.me
  CONAN_LOGIN_USERNAME: appveyor
  CONAN_STABLE_BRANCH_PATTERN: release/*

  CONAN_SHARED_OPTION_NAME: False
  CONAN_PURE_C: False

  matrix:

# Visual Studio 2017

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MT
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MTd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MT
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_VISUAL_RUNTIMES: MTd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

# Visual Studio 2019

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MT
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MTd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86_64
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=True,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MT
      CONAN_BUILD_TYPES: Release
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_VISUAL_RUNTIMES: MTd
      CONAN_BUILD_TYPES: Debug
      CONAN_ARCHS: x86
      CONAN_OPTIONS: xerces-c:with_unit_tests=True,xerces-c:shared=False,*:dll_sign=False

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts\\;%PATH%
  - pip install conan
  - pip install conan_package_tools

  - conan user

build: false

test_script:
  - python build.py
